language: cpp
compiler:
    - gcc
    - clang
os:
    - linux
dist:
    - trusty
env:
    global:
        - GCC_VERSION="4.8"
    matrix:
        - BUILD_TYPE=Debug
        - BUILD_TYPE=Release

script:
  - mkdir ./build
  - cd build/
  - cmake ..
  - cmake --build

notifications:
    email:
        - havyhidalgo@gmail.com



